package com.example.wejam.venue.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

import java.time.Instant;
import java.time.LocalTime;
import java.util.UUID;

/**
 * Not mapped on purpose: {@code location} (generated by Postgres from latitude/longitude) and {@code time_zone}
 * (DB default Asia/Kolkata; read when event times are checked against the curfew).
 */
@Entity
@Table(name = "venues")
public class Venue {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    @Column(name = "owner_id", nullable = false, updatable = false)
    private UUID ownerId;

    private String name;
    private String description;

    @Column(name = "address_line")
    private String addressLine;

    private String city;
    private double latitude;
    private double longitude;

    @Column(name = "fssai_number")
    private String fssaiNumber;

    @Enumerated(EnumType.STRING)
    @Column(name = "hosting_mode")
    private HostingMode hostingMode;

    @Enumerated(EnumType.STRING)
    @Column(name = "sound_policy")
    private SoundPolicy soundPolicy;

    @Column(name = "sound_curfew")
    private LocalTime soundCurfew;

    @Column(name = "house_rules")
    private String houseRules;

    @Enumerated(EnumType.STRING)
    @Column(name = "verification_status")
    private VerificationStatus verificationStatus = VerificationStatus.PENDING;

    @Column(name = "rejection_reason")
    private String rejectionReason;

    @CreationTimestamp
    @Column(name = "created_at", updatable = false)
    private Instant createdAt;

    @UpdateTimestamp
    @Column(name = "updated_at")
    private Instant updatedAt;

    protected Venue() {
    }

    public Venue(UUID ownerId) {
        this.ownerId = ownerId;
    }

    public void updateDetails(String name, String description, String addressLine, String city,
                              double latitude, double longitude) {
        this.name = name;
        this.description = description;
        this.addressLine = addressLine;
        this.city = city;
        this.latitude = latitude;
        this.longitude = longitude;
    }

    public void updatePolicies(HostingMode hostingMode, SoundPolicy soundPolicy, LocalTime soundCurfew,
                               String houseRules) {
        this.hostingMode = hostingMode;
        this.soundPolicy = soundPolicy;
        this.soundCurfew = soundCurfew;
        this.houseRules = houseRules;
    }

    /** A verification covers one license number, so a different number needs verifying again. */
    public void changeFssaiNumber(String fssaiNumber) {
        if (fssaiNumber.equals(this.fssaiNumber)) {
            return;
        }
        this.fssaiNumber = fssaiNumber;
        this.verificationStatus = VerificationStatus.PENDING;
        this.rejectionReason = null;
    }

    public UUID getId() {
        return id;
    }

    public UUID getOwnerId() {
        return ownerId;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public String getAddressLine() {
        return addressLine;
    }

    public String getCity() {
        return city;
    }

    public double getLatitude() {
        return latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public String getFssaiNumber() {
        return fssaiNumber;
    }

    public HostingMode getHostingMode() {
        return hostingMode;
    }

    public SoundPolicy getSoundPolicy() {
        return soundPolicy;
    }

    public LocalTime getSoundCurfew() {
        return soundCurfew;
    }

    public String getHouseRules() {
        return houseRules;
    }

    public VerificationStatus getVerificationStatus() {
        return verificationStatus;
    }

    public String getRejectionReason() {
        return rejectionReason;
    }
}
